app:
  name: "{{AppName}}"

  author: "Hofstadter <support@hofstadter.io>"
  license: "BSD 3-Clause"

  homepage: "https://github.com/hofstadter-io/hof-starter-app-minimal"

  keywords:
    - "Hofstadter"
    - "Studios"
    - "HofStarterApp"
    - "hof-starter-app"
    - "minimal"

